### ISSUE TITLE
Missing transition error message is not self-explanatory

### ISSUE THREAD

**Issue by szczeles** [getindata/doge-datagen#12]
In case of a missing transition in the graph, the process starts, but fails with strange exception:

```
Data generation start: 2022-03-31 06:48:57.607972
Traceback (most recent call last):
  File "/train.py", line 227, in <module>
    generate_bots_activity(40, clickstream_sink, start_user_id_at=1000000)
  File "/train.py", line 201, in generate_bots_activity
    bot_activity.start()
  File "/usr/local/lib/python3.8/site-packages/doge_datagen/doge.py", line 227, in start
    self.__tick()
  File "/usr/local/lib/python3.8/site-packages/doge_datagen/doge.py", line 194, in __tick
    trigger = self.__random_trigger(state)
  File "/usr/local/lib/python3.8/site-packages/doge_datagen/doge.py", line 212, in __random_trigger
    for key, probability in self.probability_matrix[state].items():
KeyError: 'main_page'
```

Consider validating of the graph completeness or make the error more human-readable, like "There is nowhere to go from [main_page]"

**Comment by gliter** [comment]
I think having a state that there is nowhere to go should be fine and not cause an error. It might be desirable to having a final state.
Some warning during validation could be shown.

**Comment by szczeles** [comment]
@gliter That's right. In this case there was a state that I reached, but there was no transition from that state.

**Comment by gliter** [comment]
https://github.com/getindata/doge-datagen/pull/14
